### ISSUE TITLE
How to deal with the “RuntimeError: Invalid VFVS_WORKUNIT and/or VFVS_WORKUNIT_SUBJOB” isssue

### ISSUE THREAD

**Issue by TobiasWinter97** [VirtualFlow/VFVS#31]
Hi there, I'm using the WSL to run the VFVS workflow, but I encountered some problems, please help me out, thanks!
$python3.9 ./vfvs_run.py
/tmp/tmp9bzrr3ir
Traceback (most recent call last):
  File "/home/tangli83/VFVS_GK/tools/templates/./vfvs_run.py", line 1928, in <module>
    main()
  File "/home/tangli83/VFVS_GK/tools/templates/./vfvs_run.py", line 1923, in main
    process(ctx)
  File "/home/tangli83/VFVS_GK/tools/templates/./vfvs_run.py", line 1767, in process
    workunit_id, subjob_id =  get_workunit_information()
  File "/home/tangli83/VFVS_GK/tools/templates/./vfvs_run.py", line 1714, in get_workunit_information
    raise RuntimeError(f"Invalid VFVS_WORKUNIT and/or VFVS_WORKUNIT_SUBJOB")
RuntimeError: Invalid VFVS_WORKUNIT and/or VFVS_WORKUNIT_SUBJOB

**Comment by akshat998** [comment]
Hi @TANGLi83-star,

VirtualFlow is primarily developed for Linux environments and may not be fully compatible with Windows. This could be contributing to the issues you're encountering. I would recommend trying VirtualFlow on a Linux-based system to see if that resolves the problem.

Best regards,
Akshat
